name: deploy

on: 
  push: 
    branches: [ main ]

  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs: 

  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  Linter: 
    runs-on: ubuntu-18.04

    steps: 
      - name: checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: programmingwithalex/pylinter@v1.4.3
        with:
          flake8-flags: '--count --show-source --statistics --ignore=E501'

  Test: 
    runs-on: ubuntu-18.04

    steps:
      - name: checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      
      - name: Test source repo
        uses: actions/setup-python@v3
        with: 
          python-version: '3.8'
        
        run: python app.py


  Deploy:

    needs: [Linter, Test]
    runs-on: ubuntu-18.04

    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          first_ssh: |
            echo 'Start'
          scp: |
            'hola.txt' => /home/${{ secrets.DC_USER }}
          last_ssh: |
            echo 'End'
