name: deploy

on: 
  push: 
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs: 
  Linter: 
    runs-on: ubuntu-18.04

    steps: 
      - name: checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Lint
      #   uses: programmingwithalex/pylinter@v1.4.3
      #   with:
      #     flake8-flags: '--count --show-source --statistics --ignore=E501'
      


      # - name: ssh scp ssh pipelines
      #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      #   env:
      #     WELCOME: "ssh scp ssh pipelines"
      #     LASTSSH: "Doing something after copying"
      #     INPUT_PORT: ${{ secrets.DC_PORT }}
      #   with:
      #     host: ${{ secrets.DC_HOST }}
      #     user: ${{ secrets.DC_USER }}
      #     pass: ${{ secrets.DC_PASS }}
      #     port: ${{ secrets.DC_PORT }}
      #     connect_timeout: 10s
      #     first_ssh: |
      #       rm -rf /home/github/test
      #       ls -la  \necho $WELCOME 
      #       touch /home/test1.txt 
            
      #     scp: |
      #       'hola.txt' => /home/
      #     last_ssh: |
      #       echo $LASTSSH

      # - uses: AbleLincoln/push-to-sftp@v1.0
      #   with:
      #       host:     ${{ secrets.DC_HOST }}
      #       username: ${{ secrets.DC_USER }}
      #       password: ${{ secrets.DC_PASS }}
      #       port:     ${{ secrets.DC_PORT }}
      #       local-dir: ./
      #       server-dir: ./home/
      # - name: Install ssh
      #   run: sudo systemctl status ssh && sudo apt-get install sshpass 

      # - name: ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host:     ${{ secrets.DC_HOST }}
      #     username: ${{ secrets.DC_USER }}
      #     password: ${{ secrets.DC_PASS }}
      #     port:     ${{ secrets.DC_PORT }}
      #     script: whoami

      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          first_ssh: |
            ls -a
          scp: |
            'hola.txt' => /home/administrator
          last_ssh: |
            echo $LASTSSH 

        # run: sshpass -p ${{ secrets.DC_PASS }} shh ${{ secrets.DC_USER }}@${{ secrets.DC_HOST }} -p ${{ secrets.DC_PORT }} "ls"
        # run: shh ${{ secrets.DC_USER }}@${{ secrets.DC_HOST }} -p ${{ secrets.DC_PORT }} "ls"
      
      - run: ls -a

      # - uses: actions/setup-python@v3
      #   with: 
          # python-version: '3.8'
      # - run: python app.py



      