name: deploy

on: 
  push: 
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs: 
  Linter: 
    runs-on: ubuntu-18.04

    steps: 
      - name: checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: programmingwithalex/pylinter@v1.4.3
        with:
          flake8-flags: '--count --show-source --statistics --ignore=E501'
      


      # - name: ssh scp ssh pipelines
      #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      #   env:
      #     WELCOME: "ssh scp ssh pipelines"
      #     LASTSSH: "Doing something after copying"
      #     INPUT_PORT: ${{ secrets.DC_PORT }}
      #   with:
      #     host: ${{ secrets.DC_HOST }}
      #     user: ${{ secrets.DC_USER }}
      #     pass: ${{ secrets.DC_PASS }}
      #     port: ${{ secrets.DC_PORT }}
      #     connect_timeout: 10s
      #     first_ssh: |
      #       rm -rf /home/github/test
      #       ls -la  \necho $WELCOME 
      #       touch /home/test1.txt 
            
      #     scp: |
      #       'hola.txt' => /home/
      #     last_ssh: |
      #       echo $LASTSSH

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host:     ${{ secrets.DC_HOST }}
          username: ${{ secrets.DC_USER }}
          password: ${{ secrets.DC_PASS }}
          port:     ${{ secrets.DC_PORT }}
          scp_source: hola.txt
          scp_target: ~/
          before_script: |
            touch hola2.txt
          after_script: |
            whoami

      # - uses: actions/setup-python@v3
      #   with: 
          # python-version: '3.8'
      # - run: python app.py



      