name: deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  PyLine: 
    runs-on: ubuntu-18.04

    steps: 
      - name: checkout source repo
        uses: actions/checkout@v3

      # - uses: actions/setup-python@v3
      #   with: 
          # python-version: '3.8'
      # - run: python app.py


      - name: linting
        uses: programmingwithalex/pylinter@v1.4.3
        with:
          flake8-flags: '--count --show-source --statistics'
      